### ISSUE TITLE
Trying to get property 'type' of non-object

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/VersionControl#25]
Hi @teppokoivula - I am seeing these errors in my Tracy error logs:

https://mysite.com/admin/setup/version-control/page?pages_id=1342&settings%5Bempty%5D=true&settings%5Brender%5D=HTML

PHP Notice: Trying to get property 'type' of non-object in /var/www/html/site/modules/VersionControl/ProcessVersionControl.module:662

Please let me know if you need anything else to track down the cause.

**Comment by teppokoivula** [comment]
Hey @adrianbj! Could you specify which version of the module you're using? :)

Error message points to line 662 of ProcessVersionControl.module, but the code on that line in the latest versions doesn't seem to match the problem:

- https://github.com/teppokoivula/VersionControl/blob/master/ProcessVersionControl.module#L662
- https://github.com/teppokoivula/VersionControl/blob/dev/ProcessVersionControl.module#L662

In the 2.0 branch (which is a legacy thing and will be going away anyway) ProcessVersionControl.module has less than 662 lines so that's probably not it 😅

**Comment by adrianbj** [comment]
Hi @teppokoivula - I am running 2.1.6

This is the line in question:
```
if ($diff && wire('fields')->get($field)->type instanceof FieldtypeFile) $diff = "";
```

Should I just "update" to v1.2.12 ?

**Comment by teppokoivula** [comment]
Hey @adrianbj. I think you'd find the "dev" branch more suitable if you're already on 2.x It's essentially an updated version of the 2.x branch, and it will completely replace the master soon(ish). Current version there is 2.2.7.

I've deprecated the "2.0" branch (in GitHub) in favor of a more long-lived dev/master strategy. I did drop support (at least officially) to some older PW versions in the dev branch though, so I hope that this isn't a terribly old site.

I'll likely keep updating the master branch (1.x, which has an older UI etc.) with some critical fixes, but that's just about it :)

**Comment by adrianbj** [comment]
Thanks @teppokoivula 

I just installed the dev branch, but I am getting these errors:

![image](https://user-images.githubusercontent.com/871211/64439005-eef47b80-d07d-11e9-8a85-44a3728fdb09.png)

![image](https://user-images.githubusercontent.com/871211/64439046-003d8800-d07e-11e9-90e5-70918014e23a.png)

![image](https://user-images.githubusercontent.com/871211/64439218-54486c80-d07e-11e9-95ad-9e76dfd87cea.png)

and I don't see the version control icon to access old versions.

Any thoughts?

Thanks.

**Comment by teppokoivula** [comment]
Oh wow. I can honestly say that I've never even seen some of those errors 😅

\VersionControl\CleanupModuleConfig and \VersionControl\ModuleConfig are new files added recently, so it could be some kind of cache issue, or it could be that the files are simply not getting loaded properly. First thing to try would be a) checking that the files for these two exist, and b) flushing the modules cache.

If that doesn't help, I'm not quite sure what to do next. I've done some testing (updating from earlier versions etc) but never had this happen – though not positive that I've tried updating from earlier 2.0 branch versions to newer "dev" versions.

I'm currently on the road, but I hope to get back to this during the weekend.

**Comment by adrianbj** [comment]
I have reverted to 2.1.6 to get rid of all the errors, but let me do some testing on a sandbox site to see if I can replicate and find the cause.

**Comment by teppokoivula** [comment]
Thanks!

Looking closer at the error messages it could have something to do with the fact that the modules "wiring" these classes are in the ProcessWire namespace, while the classes being wired are in the VersionControl namespace. It could also be something really obvious, but I'm too tired to figure it out right now – if you find something that'd be great, but this definitely looks like something that needs to be resolved before I can merge the dev branch to master. There are some pretty major changes there, which is why I've been pushing it forward, as I haven't had the time to test it all properly... :)

**Comment by teppokoivula** [comment]
Just for the record, the classLoader stuff that _should_ handle loading/finding these files is here: https://github.com/teppokoivula/VersionControl/blob/dev/VersionControl.module#L190:L198.

**Comment by adrianbj** [comment]
Yeah, I just came to the same conclusion about it being a namespace issue. I haven't used the ClassLoader before though, so I think I might just leave it to you to figure out if that's ok :)

Tested on a second site though and definitely seeing the same issues so if you can't actually reproduce let me know and I can spend some more time on it.

**Comment by adrianbj** [comment]
Not sure what has changed, but I just tried updating from the 2.0 to dev branch and this time there don't seem to be any problems and so far it looks like the original "Trying to get property 'type' of non-object" is gone. I'll keep monitoring, but so far so good.

**Comment by teppokoivula** [comment]
Great to hear.

I fixed a different issue a couple of days ago and stumbled into something similar. Initial issue was a call to Modules::setModuleConfigData() with wrong param type (string instead of Module), while another issue was attempting to use a VersionControl namespaced class in constructor *before* classLoader had any knowledge of the VersionControl namespace.

Not sure why these weren't bothering me earlier, but they showed up instantly this time, and were thus pretty simple to track down :)
