### ISSUE TITLE
implode(): Argument #1 ($pieces) must be of type array, string given

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/VersionControl#39]
Hi @teppokoivula - I've been getting this when trying to remove fields from templates. It prevents me from removing the fields.

![image](https://user-images.githubusercontent.com/871211/137036908-4d4ec7d7-46ea-461f-a3cd-04f7cfd492cd.png)

I assume this is a PHP8 only issue, but not certain.

**Comment by teppokoivula** [comment]
@adrianbj, after looking into this I'm pretty sure it's actually fixed in current versions of the module. Could you double check that you're using the latest version available?

It looks like that code might be from some earlier version of VC 2.0, perhaps from the (now deprecated and removed) 2.0 branch.

**Comment by adrianbj** [comment]
Hi @teppokoivula - sorry about this report - it happened on a dev version of site and I hadn't updated this module there (even though it was updated on the live version).
