### ISSUE TITLE
PagePathHistory::getPage() - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language_id' in 'field list'

### ISSUE THREAD

**Issue by q2apro** [teppokoivula/VersionControl#4]
Having many of such erros in my logs: 

    PagePathHistory::getPage() - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language_id' in 'field list'

Seems to come with the URL `en/http404`.

How to fix that?

**Comment by teppokoivula** [comment]
PagePathHistory is part of ProcessWire's core package, and in no way directly related to VersionControl. Unless you've got a good reason to suspect that this error is caused by VersionControl, I'd suggest opening an issue at the [ProcessWire repository](https://github.com/ryancramerdesign/ProcessWire/issues) instead.

Please let me know if there's something I'm missing here, though!

**Comment by q2apro** [comment]
Thanks for letting me know. Opened the issue over there: https://github.com/ryancramerdesign/ProcessWire/issues/2011
