### ISSUE TITLE
Can version history be persisted for deleted pages?

### ISSUE THREAD

**Issue by TrevorPage** [teppokoivula/VersionControl#8]
The question I have concerns version history of pages that are deleted. My understanding from reading the documentation some months ago was that, if a page of content is deleted, then the corresponding VCS history is deleted. 

Essentially the basic requirement is to be able to track and potentially restore deleted content. Is that a possibility?

**Comment by teppokoivula** [comment]
A bit of a late reply, but this depends on whether "delete all stored data for deleted pages" is checked in module configuration screen. This is checked by default and there's no easy way to restore deleted pages via this module, but stored data doesn't *have to* be deleted.

On the other hand there's no built-in support for restoring deleted pages. It's definitely something to consider in the future, but currently it would require quite a bit of manual work.

Since this is mainly a question, I'm closing this issue for now.
