### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by jmartsch** [teppokoivula/VersionControl#9]
Installing this module in my ProcessWire 3.0.42 (on Windows 10 XAMPP) throws the following error:
Call to undefined function finfo_open() 
 ...\site\modules\VersionControl\VersionControl.module:844
$finfo = finfo_open(FILEINFO_MIME_TYPE);
But after reloading the page the error does not appear.

**Comment by teppokoivula** [comment]
The problem is that `finfo_open()`, which is used to identify MIME types for stored files, is part of the PECL fileinfo extension. According to [the PHP docs](http://php.net/manual/en/fileinfo.installation.php) this extension enabled by default, *except* in Windows:

> Windows users must include the bundled php_fileinfo.dll DLL file in php.ini to enable this extension.

Detecting MIME type is not currently a necessity, but it was intended to be part of certain future features. I've got a workaround for this issue, but will need to test it a bit before committing.

Thanks for reporting this issue!

**Comment by teppokoivula** [comment]
I've just committed an update that should fix this issue.

The module will still attempt to use the finfo_open() + finfo_file() approach for MIME type detection, but if that fails it'll fall back to the mime_content_type() function.. and if that fails too, it'll avoid unnecessary errors by storing an empty string.

Please let me know if the issue persists, though!

**Comment by jmartsch** [comment]
Issue is solved. Thank you very much :)
